### ISSUE TITLE
HTTP ERROR 500 after active

### ISSUE THREAD

**Issue by h2kyaw** [MyBBStuff/MyAlerts#268]
My forum got "HTTP ERROR 500" error after I active MyAlerts

I installed:

MyAlerts: (2.0.4)
Thank You/Like System: (3.3.6)
MentionMe (3.2.12)

I can't active them at the same time?

Firstly I active MyAlerts and than active MentionMe and than Thank System but my forum got error 500 :(

After I deactivated MyAlerts form can run again. 👎

**Comment by euantorano** [comment]
Please check your server error log and post the contents here. A HT

**Comment by h2kyaw** [comment]
referer: https://localhost.com/
[Fri May 29 16:41:19.989590 2020] [proxy_fcgi:error] [pid 11552:tid 140553224132352] [client 162.158.165.235:50518] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'OUGC_Awards_MyAlerts_Formatter' not found in projectX/inc/plugins/ougc_awards.php:1996\nStack trace:\n#0 projectX/inc/class_plugins.php(142): ougc_awards_global_start('')\n#1 projectX/global.php(100): pluginSystem->run_hooks(Array)\n#2 projectX/index.php(18): require_once('/var/www/vhosts...')\n#3 {main}\n  thrown in projectX/inc/plugins/ougc_awards.php on line 1996'
[Fri May 29 16:42:11.810615 2020] [proxy_fcgi:error] [pid 11554:tid 140553173776128] [client 172.69.135.81:50594] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'OUGC_Awards_MyAlerts_Formatter' not found in projectX/inc/plugins/ougc_awards.php:1996\nStack trace:\n#0 projectX/inc/class_plugins.php(142): ougc_awards_global_start('')\n#1 projectX/global.php(100): pluginSystem->run_hooks(Array)\n#2 projectX/index.php(18): require_once('/var/www/vhosts...')\n#3 {main}\n  thrown in projectX/inc/plugins/ougc_awards.php on line 1996'

**Comment by euantorano** [comment]
Looks like the problem is coming from the OUGC Awards plugin, which tries to integrate with MyAlerts. Ping @Sama34: any idea?

**Comment by h2kyaw** [comment]
Yes bro@euantorano  MyAlerts Integration is Active and I try Deactivate and didn't work too :(

**Comment by euantorano** [comment]
Hopefully Omar can help. I'm not too familiar with OGUC Awards I'm afraid.

**Comment by h2kyaw** [comment]
> Hopefully Omar can help. I'm not too familiar with OGUC Awards I'm afraid.

It's Okay I can wait :") coz I want to use xD

**Comment by Sama34** [comment]
You installed MyAlerts after OUGC Awards, right? This is a common problem with all plugins that integrate with MyAlerts. Simply deactivate and activate OUGC Awards back.

The same would probably apply for any other plugin that integrates with MyAlerts installed before MyAlerts itself.

**Comment by h2kyaw** [comment]
I try to install MyAlerts first after that I installed OUGC Awards.
